#!/bin/bash

# Function to process a single package's README
process_package_readme() {
  local package_dir="$1"
  local package_name=$(basename "$package_dir")
  local readme_path="$package_dir/README.md"
  local header_path="$package_dir/HEADER.md"
  local temp_file=$(mktemp)
  local copyright_line="Copyright (c) 2019 BunnyWay d.o.o."

  echo "Processing $package_name..."

  # Check if README.md exists
  if [ ! -f "$readme_path" ]; then
  echo "WARNING: README.md not found in $package_dir"
  return
  fi

  # Start with an empty temp file
  > "$temp_file"

  # If HEADER.md exists and its content isn't already in README.md, prepend it
  if [ -f "$header_path" ]; then
  if ! grep -q "$(head -n 1 "$header_path")" "$readme_path"; then
  cat "$header_path" > "$temp_file"
  printf "\n---\n\n" >> "$temp_file"
  fi
  fi

  # Process the README content: remove duplicates and exclude the sourcedocs line
  # Also exclude the copyright line if it exists
  awk -v copyright="$copyright_line" '
    # Skip the sourcedocs line and copyright line
    /This file was generated by \[SourceDocs\]/ { next }
    $0 == copyright { next }
    # Print only if not seen before
    !seen[$0]++
  ' "$readme_path" >> "$temp_file"

  # Add copyright at the bottom if it's not already there
  if ! grep -q "$copyright_line" "$readme_path"; then
  printf "\n%s\n" "$copyright_line" >> "$temp_file"
  fi

  # Replace original file with processed content
  mv "$temp_file" "$readme_path"
  chmod 644 "$readme_path"

  echo "✓ Processed $package_name successfully!"
}

# Main script
REFERENCE_DIR="Documentation/Reference"

# Check if Reference directory exists
if [ ! -d "$REFERENCE_DIR" ]; then
echo "ERROR: Reference directory not found at $REFERENCE_DIR"
exit 1
fi

# Process each package directory in Reference
echo "Starting package processing..."
for package_dir in "$REFERENCE_DIR"/*/ ; do
if [ -d "$package_dir" ]; then
process_package_readme "$package_dir"
fi
done

echo "All packages processed successfully!"
